alpaka-group/cupla

- .gitmodules
- include/cupla/manager/Device.hpp
- update sub module alpaka to the latest `develop` version
- update usage of `getDevByIdx<>()`
- update usage of `getDevCount<>()`
> Topic update to new alpaka

- doc/PortingGuide.md
This pull request update the documentation for extern shared memory top be consistent with #25
> update docu of extern shared memory

- include/cupla/cudaToCupla/runtime.hpp
added some makros to replace some cuda math functions (fabsf,expf,logf,rsqrt,fdivides) with the alpaka equivalents.
> Topic adding math makros to cupla

- include/cupla/cudaToCupla/runtime.hpp
only overwrite math instrinsics if we not run a CUDA kernel
> diasble intrinsic overwrite in CUDA kernels

- .travis.yml
- add compile time tests
- add runtime tests
> add example `vectorAdd` to travis

- cuplaConfig.cmake
- include/cupla/types.hpp
allow to force synchron streams execution with a cmake flag
> add cmake switch `CUPLA_STREAM_ASYNC_ENABLED`

- include/cupla/cudaToCupla/driverTypes.hpp
- include/cupla_driver_types.hpp
- add new `cuplaError` types
- add C++ std exeption handling for `cuplaError`
> add new `cuplaError` types

- src/common.cpp
delete last error if cuda is used
> reset last error if cuda is used

- include/cupla/manager/Device.hpp
- include/cupla_driver_types.hpp
- src/device.cpp
- handle more error cases
- use C++ std exeptions
> extent device handling

- include/cupla/c/datatypes/cuplaExtent.hpp
- include/cupla/c/datatypes/cuplaPos.hpp
- include/cupla/datatypes/uint.hpp
- include/cupla/types.hpp
- src/memory.cpp
- update alpaka to latest develepment branch
- use new alpaka namespace `alpaka::Vec<>` -> `alpaka::vec::Vec<>`
> Topic sub module update to alpaka latest dev

- INSTALL.md
Mention TBB in `INSTALL.md`. Follow-up to #69
> Docs: INSTALL.md mention TBB

- include/cupla/version.hpp
> add versioning file

- include/cupla/version.hpp
fix wrong copyright year added in #74
> fix copyright year

- .rodare.json
- CHANGELOG.md
Added an announcement text for the 0.1.0 "Worf" release.
Also adds the [RODARE](https://rodare.hzdr.de) metadata.
> Changelog 0.1.0

- .gitmodules
> Updates alpaka to 0.3.5.

- include/cupla/api/common.hpp
follow up of #83
- update documentation string
> update documentation of `cuplaGetLastError`

- .travis.yml
update CUDA to fulfill the new ALPAKA requirements needed for #89
> CI: update CUDA from 7.5 to 8.0

- cuplaConfig.cmake
- include/cupla/datatypes/uint.hpp
- include/cupla/types.hpp
- src/common.cpp
Introduce the alpaka HIP backend.
> alpaka backend: HIP

- include/cupla/c/datatypes/cuplaPitchedPtr.hpp
> fix -Wreorder in cuplaPitchedPtr

- .gitlab-ci.yml
prefix test executions with the bash tool `time`
> execution runtime for CI tests

- doc/PortingGuide.md
This was found during investigation of #131 .
> Clarify documentation of inclusion order

- include/cupla/config/CpuOmp2Blocks.hpp
- include/cupla/config/CpuOmp2Threads.hpp
- include/cupla/config/CpuSerial.hpp
- include/cupla/config/CpuTbbBlocks.hpp
- include/cupla/config/CpuThreads.hpp
- include/cupla/config/GpuCudaRt.hpp
- include/cupla/config/GpuHipRt.hpp
fix #138
Config headers and cuda renaming via defines created a invinite loop
> fix config header

- INSTALL.md
- include/cupla/config/CpuOmp4.hpp
- include/cupla/defines.hpp
- include/cupla/namespace.hpp
- include/cupla/types.hpp
allow the selection of the OMP4 alpaka backend
> support for alpaka OMP4 backend

- include/cupla/kernel.hpp
- Remove macros to execute kernel (left over from C++98)
The interface for the user to start kernel is not changed!
> refactor cupla kernel execution

- doc/PortingGuide.md
As [previously decided](https://github.com/ComputationalRadiationPhysics/cupla/issues/121#issuecomment-581946425).
> Extend the docs with thread unsafety

- README.md
- add everyone who contributed to the current release
- link all mentioned persons
- upgrade @ax3l and add `Dr.`
> update author section

- INSTALL.md
- README.md
- cuplaConfig.cmake
- example/CUDASamples/asyncAPI/CMakeLists.txt
- example/CUDASamples/asyncAPI_tuned/CMakeLists.txt
- example/CUDASamples/matrixMul/CMakeLists.txt
- example/CUDASamples/vectorAdd/CMakeLists.txt
> update minimal CMake requirements to 3.11.4

- CHANGELOG.md
- cuplaConfig.cmake
- include/cupla/version.hpp
- The change-log is not containing all PR's, it is a collection of the most important changes for the user.
> changelog and version increase to 0.2.0

- include/cupla/cudaToCupla/driverTypes.hpp
This is a clone of #118 for which CI is not starting.
> Adds float3 and int3 with make-functions.

- CHANGELOG.md
- update release date
- add PR'S from the last days
> update release date for 0.2.0

- INSTALL.md
- README.md
- doc/ConfigurationHeader.md
- doc/PortingGuide.md
Link the new location of cupla.
> update cupla github links

- include/cupla/device/math/Erf.hpp
- include/cupla/device/math/Pow.hpp
Expose alpaka `math::pow` and `math::erf`.
> math functions: `erf` and `pow`

- include/cupla/manager/Stream.hpp
fix #182
The handling of the default stream and the cupla internal enumaration of
streams created a invinite loop if more than one device was used.
> fix multi GPU streams handling and default stream

- .gitlab-ci.yml
- script/compiler_base.yml
Use latest container for testing.
> CI: update container to v1.1

- alpaka/.zenodo.json
- alpaka/CHANGELOG.md
- alpaka/README.md
- alpaka/cmake/alpakaCommon.cmake
- alpaka/include/alpaka/dev/cpu/SysInfo.hpp
pull the release alpaka  0.6.0 
```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="cupla@hzdr.de" git subtree pull --prefix alpaka git@github.com:alpaka-group/alpaka.git 0.6.0 --squash
```
> update to alpaka release0.6.0

- README.md
- alpaka/.zenodo.json
- alpaka/CHANGELOG.md
- alpaka/example/openMPSchedule/src/openMPSchedule.cpp
- alpaka/include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
- alpaka/include/alpaka/kernel/TaskKernelOacc.hpp
- alpaka/test/unit/warp/src/Activemask.cpp
- alpaka/test/unit/warp/src/Ballot.cpp
Update to alpaka 0.6.1
```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="cupla@hzdr.de" git subtree pull --prefix alpaka git@github.com:alpaka-group/alpaka.git 0.6.1 --squash
```
> Topic update to latest alpaka release 0.6.1

- README.md
This PR is merged into release 0.3.0
> add badge for master
