include/cupla/manager/Memory.hpp

handle free call for `nullptr`

fiy that `nullptr` can not be freed

---

doc/PortingGuide.md
include/cupla/api/common.hpp
include/cupla/cudaToCupla/driverTypes.hpp
include/cupla/cudaToCupla/runtime.hpp
src/common.cpp

- add [`cudaPeekAtLastError`](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#error-checking)
- add several atomics:
- atomicSub
- atomicMin
- atomicMax
- atomicInc
- atomicDec
- atomicExch
- atomicCAS
- add [`__float_as_int`](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__CAST.html#group__CUDA__MATH__INTRINSIC__CAST_1g781a84bf3b7efe84969c2dc9b0915fa1) function
- proper code indentation inside `PortingGuide.md`, so that the code blocks appear indented and inside the list items

Add CUDA APIs: PeekAtLastError, int_as_float, Atomics

---

include/cupla/kernel.hpp

Quelch "unusude parameter"-warning by commenting out variable names.

quelch unused parameter warning

---

include/cupla/api/memory.hpp
include/cupla/c/datatypes/cuplaArray.hpp
include/cupla/c/datatypes/cuplaExtent.hpp
include/cupla/c/datatypes/cuplaMemcpy3DParms.hpp
include/cupla/c/datatypes/cuplaPitchedPtr.hpp
include/cupla/c/datatypes/cuplaPos.hpp
include/cupla/cudaToCupla/driverTypes.hpp
src/memory.cpp

- rename all `cuda*` types to `cupla*` and remove the cupla namespace
- move files to directory `c` that means tere are no namespaces in
- fix dependancies
This pull request is the first step to cleanup the naming:
- if CUDA use the prefix `cudaTYPE` for a type the corresponding cupla type is `cuplaTYPE`
- if cuda use no prefix for a type (e.g., TYPE)  the corresponding  cupla type is placed in the namespace `cupla::TYPE`

change cupla type nameings

---

README.md

Adds the [pronunciation](https://en.wiktionary.org/wiki/Qapla%27) of *Qapla'* ... I mean, **cupla** to the `README.md` file (UTF-8).
Adds some text highlights and an additional link to the tuning guide for people already looking for it at this point.
--
Due to the close-ness of the API it makes sense to follow the following guidelines to avoid confusion:
- http://www.nvidia.co.uk/page/trademark_info.html
- https://devtalk.nvidia.com/default/topic/376174/cuda-programming-and-performance/cuda-copyright-or-trademark-notificiation-general-rules-on-howto-use-the-cuda-name/
- https://developer.nvidia.com/cuda-zone
Also, re-implementing APIs is fair-use:
- https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.
IANAL.

README: Add Pronunciation & Formatting, CUDA®

---

include/cupla/cudaToCupla/driverTypes.hpp

allow unspecified number of arguments for atomic macros
allows the following example:
```C++
atomicAdd( ptr, 1, ::alpaka::hierarchy::Threads() );
```

add alpaka hierarchy atomics support

---

include/cupla/kernel.hpp
include/cupla/traits/IsThreadSeqAcc.hpp
include/cupla/types.hpp

- add trait `IsThreadSeqAcc`
- change internal methods to queue a kernel
- add `AccThreadSeq` accelerator
**more details:**
- if one accelerator is enabled `cupla::AccThreadSeq` is equal to `cupla::Acc`
- This pull request allow under special conditions to enable two accelerators.
This double selection is only useful for porting CUDA code to cupla.
conditions:
- one accelerator must be work fully sequential in the thread level
- the other must be support a arbitrary number of threads in the thread level
- `CUPLA_KERNEL_OPTI` use always `cupla::AccThreadSeq` as accelerator

add support for two accelerators

---

include/cupla/cudaToCupla/runtime.hpp

- remove `fabsf()`
- remove `rsqrtf()`
The definition of math function with macros can create conflicts with other libraries.
If math functions are needed the native **alpaka** functions can be used.

remove defines for math functions

---

cmake/addExecutable.cmake
cuplaConfig.cmake
example/CUDASamples/asyncAPI/CMakeLists.txt
example/CUDASamples/asyncAPI_tuned/CMakeLists.txt
example/CUDASamples/matrixMul/CMakeLists.txt
example/CUDASamples/vectorAdd/CMakeLists.txt

- add `cupla_add_executable` to simplify the handling of cupla intern source files
- use `cupla_add_executable()` in all examples
- use `cupla_LIBRARIES` instead of cupla internal variable

Topic add executable

---

include/cupla/datatypes/uint.hpp

This specification helps during the porting phase from CUDA to cupla. It is possible to include the cupla header and remove cupla redefinition. In that case it is possible to call `threadIdx`, ... without the need of an alpaka accelerator.
```
#include <cuda_to_cupla.hpp>
#if( ALPAKA_ACC_GPU_CUDA_ENABLED == 1 )
#endif
```

conversion CUDA native dim3->cupla::uint3

---

INSTALL.md
cuplaConfig.cmake

- allow the usage of an extern alpaka by setting `cupla_ALPAKA_PROVIDER`
- call `git submodule init` only if internal alpaka is used

add advanced cmake var `cupla_ALPAKA_PROVIDER`

---

include/cupla/c/datatypes/cuplaExtent.hpp
include/cupla/c/datatypes/cuplaMemcpy3DParms.hpp
include/cupla/c/datatypes/cuplaPitchedPtr.hpp
include/cupla/c/datatypes/cuplaPos.hpp
include/cupla/datatypes/uint.hpp

remove location prefix for default constructor
```
/home/widera/src/cupla/include/cupla/c/datatypes/cuplaPitchedPtr.hpp(34): warning: __host__ annotation on a defaulted function("cuplaPitchedPtr") is ignored
```

fix warning: CUDA 9

---

include/cupla/manager/Event.hpp
include/cupla/manager/Stream.hpp

The id for events and streams is not unique as soon as on element is deleted.
- add static id counter within the factory methods to create a unique id

fix id generation for events and streams

---

src/common.cpp

If CUDA is used and `cuplaGetLastError` is called the return code was not returned.

fix `cuplaGetLastError`

---

include/cupla/api/stream.hpp
include/cupla/cudaToCupla/runtime.hpp
src/stream.cpp

fix #82
- add function `cuplaStreamQuery`
- add renaming definition from `cudaStreamQuery` to `cuplaStreamQuery`
Signed-off-by: René Widera <r.widera@hzdr.de>

add `cuplaStreamQuery()`

---

include/cupla/api/common.hpp
src/common.cpp

queried in #82
Implement `cuplaPeekAtLastError()` for the cuda backend.

implement `cuplaPeekAtLastError()`

---

include/cupla_driver_types.hpp
src/common.cpp

The function `cuplaGetErrorString` was available but not implemented.
- refactor `CuplaErrorCode` to support `const char*` as return type
- implement `cuplaGetErrorString()`

add implementation for `cuplaGetErrorString`

---

include/cupla/types.hpp

Due to the wrong used define name for the TBB backend it was not possible to use it.

fix TBB backend activation

---

.travis.yml

For #89 the minimum clang version must be 4.0
- use clang 4.0 for CI tests

CI: switch from clang 3.5 to 4.0

---

include/cupla/kernel.hpp

- update alpaka to c922a19c2acfd743e1251680dc2b87863ee1549b
- dependency changes: rename `createTaskExec` -> `createTaskKernel` cherry picked from #101

update to latest alpaka develop

---

include/cupla/traits/IsThreadSeqAcc.hpp

This lets `CUPLA_KERNEL_OPTI` swap the threads and elements when using the TBB backend, as it does for the serial and OpenMP ones.

Mark the TBB backend as "thread sequential"

---

cmake/addExecutable.cmake

- it removes the unnecessary scope of the function for `CUPLA_ADD_EXECUTABLE`
- especially needed for HIP
Edit: ... otherwise linking with HIP will fail due to a messed up cmake command

Changes function to macro 'CUPLA_ADD_EXECUTABLE'.

---

INSTALL.md
README.md

- fixes alpaka link in README.md
Refers to request in #103.
Also changed `Alpaka -> alpaka` in INSTALL.md to be consistent with README.md

Describes how to pull subtree as generic git author.

---

.travis.yml
README.md
doc/ConfigurationHeader.md
include/cupla/config/CpuOmp2Blocks.hpp
include/cupla/config/CpuOmp2Threads.hpp
include/cupla/config/CpuSerial.hpp
include/cupla/config/CpuTbbBlocks.hpp
include/cupla/config/CpuThreads.hpp
include/cupla/config/GpuCudaRt.hpp
include/cupla/config/GpuHipRt.hpp
include/cupla/defines.hpp
src/common.cpp
src/device.cpp
src/event.cpp
src/manager/Driver.cpp
src/memory.cpp
src/stream.cpp
test/system/config/kernel.cpp
test/system/config/main.cpp
test/system/config/test.sh

This PR substitute #109
- add configuration header
- add pre-compiler define to use cupla as header only library
- add documentation
- add tests
CC-ing: @fwyzard

configuration header

---

.gitlab-ci.yml

The  `gitlab-ci.yml` file is executed when a gitlab mirror is configured. At the moment I have configured a mirror for my fork.
[Gitlab Mirror](https://gitlab.com/hzdr/cupla/)
[Gitlab CI Results](https://github.com/SimeonEhrig/cupla/commits/init-gitlab-ci) (old CI results were erased because of a rebase action)
Docker containers are used for the build and test environment. The docker files of the environments are stored in this [repo](https://gitlab.com/hzdr/cupla-docker/). The repo automatically build and uploads the docker images to a docker registry.

Add GitLab CI Tests

---

.travis.yml

update travis cmake version
This update is required for #128 to switch to the latest alpaka dev branch

update travis CMake to 3.15.4

---

include/cupla/cudaToCupla/driverTypes.hpp

I feel it was not clear that cupla atomics take one more parameter compared to their CUDA counterparts, so extended the comments to explain it.

Extend comments of atomic functions

---

include/cupla/manager/Device.hpp
src/event.cpp

These two are popping when building PIConGPU `dev` branch. (There might be more of this sort.)

Fix warnings concerning type casting

---

src/memory.cpp

Prepare memory allocated with `cuplaMallocHost` to support memory pinning for all accelerator if alpaka is supporting the functionality.

pin memory allocated with `cuplaMallocHoast`

---

.travis.yml

fix #133
Use minimal required CMake version for travis tests

use CMake 3.11.4 for travis tests

---

include/cupla/kernel.hpp

Remove section about swapping element and thread layer.
Bug was introduced with #136
thx @sbastrakov for catching the wrong documentation.

fix `KernelWithElementLevel` documentation

---

include/cupla/device/Atomic.hpp
include/cupla/device/Index.hpp
include/cupla/device/Synchronization.hpp

Move all device implementations into the inline namespace `CUPLA_ACCELERATOR_NAMESPACE`
This bug becomes visible in PIConGPU wenn using #162 and #160 together. Since math functions are template based a math function must be used to trigger the bug.

fix ambiguous namespace `device`

---

example/CUDASamples/blackScholes/src/BlackScholes_gold.cpp
include/cupla/cudaToCupla/runtime.hpp
include/cupla/defines.hpp
include/cupla/device/math/Common.hpp

- change function attribute from `ALPAKA_FN_ACC` to `ALPAKA_FN_HOST_ACC`
- map host side math functions to alpaka stl math functions
- add precompiler define to handle device code path compilation e.g. with CUDA or HIP.
The previous implementation of math function was not working correctly in PIConGPU due to the function attributes. The older implementation also not allowed to write a functor which can be used on device and host. This is now fixed, if you call a cupla math function within the host compile path of the compiler it will always map function calls to the alpaka stl math implementations. 
Internally we discussed to implement this into PMacc cupla users should also be able to implement a functor which can be used on device and the host.

refactor math functions

---

.gitlab-ci.yml
script/compiler_base.yml
script/run_test.yml

New container generator for the GitLab CI tests.
See: https://gitlab.com/hzdr/crp/alpaka-group-container

Change docker images for GitLab CI tests

---

src/event.cpp
src/memory.cpp
src/stream.cpp

Remove semicolons after function bodies triggering warnings with -Wpedantic.

Fix ; warnings

---

.gitlab-ci.yml
script/compiler_base.yml
script/run_test.sh

Second try to melt the CI. The original PR was aborted because of some wrong merges before: #174

Second try: Extends GitLab CI scripts to run different compiler versions

---

include/cupla/config/CpuOmp2Blocks.hpp
include/cupla/config/CpuOmp2Threads.hpp
include/cupla/config/CpuOmp4.hpp
include/cupla/config/CpuSerial.hpp
include/cupla/config/CpuTbbBlocks.hpp
include/cupla/config/CpuThreads.hpp
include/cupla/config/GpuCudaRt.hpp
include/cupla/config/GpuHipRt.hpp
test/system/config/kernel.cpp
test/system/config/main.cpp

Currently the config headers enforce the usage of CUDA renaming headers.
Since #161 the user can use plain cupla or by explicit include `cuda_to_cupla.hpp` to be able to use `cuda*` function call.

config headers: not require cupla renaming headers

---

cuplaConfig.cmake
include/cupla/config/AnyOacc.hpp
include/cupla/config/AnyOmp5.hpp
include/cupla/defines.hpp
include/cupla/namespace.hpp
include/cupla/types.hpp

Add support for Alpaka 0.6.0's [OpenMP 5](https://github.com/alpaka-group/alpaka/pull/1126) and (experimental) [OpenACC](https://github.com/alpaka-group/alpaka/pull/1127) backends.

Add support for Alpaka's OpenMP 5 and OpenACC backends

---

cuplaConfig.cmake

We do not check in CMake for supported alpaka versions. This could easily result in compile issues.
- Check the alpaka version if the external installed version is used.

check for supported alpaka version

---

.rodare.json
README.md

There was a weird capitalization.
Fix the name in rodare.json that is a copy of the header
Note this PR is for `0.3.0-rc1`, which will then be merged to `dev`.

Fix the header of the README.md
